### ISSUE TITLE
[Broken link] CONTRIBUTING not found

### ISSUE THREAD

**Issue by Aju100** [hypertrons/hypertrons-crx-website#10]
HI there, there is no info and broken link for contributing guidelines on the official website of hypertrons-crx-website.

Steps to reproduce to a README.md and click on contributing link.

Broken link:
- https://github.com/hypertrons/hypertrons-crx-website/blob/master/CONTRIBUTING.md

**Comment by heming6666** [comment]
@Aju100 Sorry for the late reply. 

Contributing guide is missing currently. It would be nice to submit a PR to fix this. we can use the [CONTRIBUTING of `Hypertrons-crx`](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) for the reference.

**Comment by Aju100** [comment]
Hi @heming6666 ,
No problem about it. Please review out the PR which I have submitted recently. #11
